// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import fs from 'fs';

const DATABASE_HOST = process.env.DB_HOST || 'mariadb';
const DATABASE_PORT = process.env.DB_PORT || '3306';
const DATABASE_NAME = process.env.MARIADB_DATABASE || 'transcendance';
const DATABASE_USER = process.env.MARIADB_USER || 'transcendance_user';
const passwordFile = process.env.MARIADB_PASSWORD_FILE;

if (!passwordFile || !DATABASE_HOST || !DATABASE_PORT || !DATABASE_NAME || !DATABASE_USER) {
  throw new Error('Mariadb environment variables are not set');
}

const DATABASE_PASSWORD = fs.readFileSync(passwordFile, 'utf8').trim() || '123';

// mysql://USER:PASSWORD@HOST:PORT/DATABASE

const DATABASE_URL = `mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // url: process.env["DATABASE_URL"],
    url: DATABASE_URL,
  },
});
