server  {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate_key /etc/nginx/ssl/chhoflac.key;
    ssl_certificate /etc/nginx/ssl/chhoflac.crt;
    server_name transcendance.fr;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    location /api/ {
        proxy_pass http://expressjs:3000;
    }
    location / {
        proxy_pass http://reactjs:5173;
    }
}