secrets:
  mysql_password: 
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

services:
  nginx:
    build:
      context: ../..
      dockerfile: srcs/docker/nginx/Dockerfile
    image: nginx:transcendance
    container_name: nginx
    ports:
      - "8443:443"
    networks:
      - transcendance
    env_file:
      - ./secrets/.env
    restart: unless-stopped
    depends_on:
      expressjs: 
        condition: service_healthy
      reactjs:
        condition: service_healthy
      mysql:
        condition: service_healthy
  reactjs:
    build:
      context: ../..
      dockerfile: srcs/docker/reactjs/Dockerfile
    image: reactjs:transcendance
    container_name: reactjs
    volumes:
      - ../frontend:/app
      - react_node_modules:/app/node_modules
    networks:
      - transcendance
    restart: unless-stopped
    env_file: secrets/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 3s
      retries: 5

  expressjs:
    build:
      context: ../..
      dockerfile: srcs/docker/expressjs/Dockerfile
    image: expressjs:transcendance
    container_name: expressjs
    volumes:
      - ../backend:/app
      - express_node_modules:/app/node_modules
    networks:
      - transcendance
    restart: unless-stopped
    env_file: secrets/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build:
      context: ../..
      dockerfile: srcs/docker/mysql/Dockerfile
    image: mysql:transcendance
    container_name: mysql_database
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - transcendance
    restart: unless-stopped
    env_file: secrets/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root"]
      interval: 5s
      timeout: 3s
      retries: 10
    secrets:
      - mysql_password
      - mysql_root_password
    
networks:
  transcendance:

volumes:
  react_node_modules:
  express_node_modules:
  mysql_data: 